[package]
name = "sexpy"
version = "0.1.0"
authors = ["Samuel Thomas <sgpthomas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "~5.0"
sexpy_derive = { path = "sexpy_derive" }

[workspace]
